const pct = (n) => `${Math.round(n)}%`

/** Build a Markdown report of one analysis (used for export). */
export function analysisToMarkdown(analysis, meta = {}) {
  const a = analysis
  const title = [a.job_title, a.company].filter(Boolean).join(" @ ") || "Target role"
  const lines = []
  lines.push(`# CVision Match Report — ${title}`)
  const stamp = meta.created_at ? new Date(meta.created_at) : new Date()
  lines.push(`_${stamp.toLocaleString()}${meta.cv_filename ? ` · ${meta.cv_filename}` : ""}${a.model ? ` · ${a.model}` : ""}_`, "")
  lines.push(`## Compatibility`, "")
  lines.push(`- **Overall match:** ${pct(a.overall_score)}`)
  lines.push(`- **ATS pass probability:** ${pct(a.ats_pass_probability)}`, "")
  if (a.verdict) lines.push(`> ${a.verdict}`, "")

  const dimNames = { technical_skills: "Technical skills", experience_depth: "Experience depth", education: "Education & credentials", role_alignment: "Role alignment" }
  lines.push("| Dimension | Score | Notes |", "|---|---|---|")
  for (const [key, label] of Object.entries(dimNames)) {
    const d = a.dimensions?.[key]
    if (d) lines.push(`| ${label} | ${pct(d.score)} | ${(d.rationale || "").replace(/\|/g, "\\|")} |`)
  }
  lines.push("")

  if (a.matched_skills?.length) {
    lines.push("## Matched skills", "")
    for (const m of a.matched_skills) lines.push(`- **${m.skill}**${m.evidence ? ` — “${m.evidence}”` : ""}`)
    lines.push("")
  }
  if (a.skill_gaps?.length) {
    lines.push("## Skill gaps", "")
    for (const g of a.skill_gaps) {
      lines.push(`- **${g.skill}** (${g.urgency} urgency${g.time_to_acquire ? `, ~${g.time_to_acquire}` : ""})${g.why_it_matters ? ` — ${g.why_it_matters}` : ""}`)
    }
    lines.push("")
  }
  if (a.weak_points?.length) {
    lines.push("## Weak points", "")
    for (const w of a.weak_points) lines.push(`- **[${w.severity}] ${w.title}** — ${w.diagnosis}`)
    lines.push("")
  }
  if (a.bullet_rewrites?.length) {
    lines.push("## Bullet rewrites (XYZ formula)", "")
    for (const r of a.bullet_rewrites) {
      lines.push(`- **Before:** ${r.original}`, `  **After:** ${r.improved}`)
      if (r.reason) lines.push(`  _Why:_ ${r.reason}`)
    }
    lines.push("")
  }
  if (a.ats_checks?.length) {
    lines.push("## ATS screen", "")
    const icon = { pass: "✅", flag: "⚠️", fail: "❌" }
    for (const c of a.ats_checks) lines.push(`- ${icon[c.status] || "•"} **${c.check}** — ${c.detail}`)
    lines.push("")
  }
  if (a.courses?.length) {
    lines.push("## Recommended courses", "")
    for (const c of a.courses) lines.push(`- [${c.title}](${c.url}) — ${c.provider}, ${c.duration || "self-paced"}, ${c.level} (+${c.match_boost}% match)`)
    lines.push("")
  }
  if (a.roadmap?.length) {
    lines.push("## Action roadmap", "")
    a.roadmap.forEach((s, i) => lines.push(`${i + 1}. **${s.title}** (${s.timeframe}) — ${s.description}`))
    lines.push("")
  }
  lines.push("---", "_Generated by CVision_")
  return lines.join("\n")
}

export function downloadText(filename, text, type = "text/markdown") {
  const url = URL.createObjectURL(new Blob([text], { type: `${type};charset=utf-8` }))
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export function reportFilename(analysis) {
  const slug = [analysis.job_title, analysis.company].filter(Boolean).join("-").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
  return `cvision-${slug || "report"}.md`
}
